USER_TARGETS := xdp-root-shim

LLC ?= llc
CLANG ?= clang
CC := gcc

LIBBPF_DIR = ../libbpf/src/
COMMON_DIR = ../common/

include $(COMMON_DIR)/common.mk

#all: xdp-root-shim

#xdp-root-shim: $(OBJECT_LIBBPF)
	#cc xdp-root-shim.c -o xdp-root-shim -lbpf -lsystemd
